"""add deleted_by to message

Revision ID: 0cde3f20ba6a
Revises: b61d57e7155a
Create Date: 2022-12-25 01:12:38.575233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cde3f20ba6a"
down_revision = "b61d57e7155a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_messages_deleted_by"), "messages", ["deleted_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_deleted_by"), table_name="messages")
    op.drop_column("messages", "deleted_by")
    # ### end Alembic commands ###
