"""index messages creation time

Revision ID: 98ce5a07b0e0
Revises: e31c353b90de
Create Date: 2022-12-20 11:43:16.034950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98ce5a07b0e0"
down_revision = "e31c353b90de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    # ### end Alembic commands ###
