"""change message read to datetime from integer

Revision ID: f07c46e346be
Revises: 0cde3f20ba6a
Create Date: 2022-12-28 19:42:04.509009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f07c46e346be"
down_revision = "0cde3f20ba6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "read",
        existing_type=sa.BOOLEAN(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "read",
        existing_type=sa.DateTime(),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
